NotebookWebApp/Controllers/NotebookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NotebookWebApp.Models;
using NotebookWebApp.ViewModels;
using System.Web.Http;

namespace NotebookWebApp.Controllers
{
    public class NotebookController : ApiController
    {
        private NotebookContext db = new NotebookContext();

        public ICollection<Notebook> Get()
        {
            return db.Notebooks.ToList();
        }

        public Notebook Get(int id)
        {
            return db.Notebooks.Find(id);
        }

        public void Put(Notebook notebook)
        {
            db.Notebooks.Add(notebook);
            db.SaveChanges();
        }

        public void Post(Notebook notebook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(notebook).State = EntityState.Modified;
                db.SaveChanges();
            }
        }

        public void Delete(int id)
        {
            Notebook notebook = db.Notebooks.Find(id);
            db.Notebooks.Remove(notebook);
            db.SaveChanges();
        }
    }
}

NotebookWebApp/Views/Content/Create.cshtml
@model NotebookWebApp.ViewModels.NotebookViewModel

@{
    ViewBag.Title = "Ноутбук";
}

<h2>Добавление нового ноутбука</h2>
<hr />
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Notebook</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notebook.Model)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Notebook.Model)
            @Html.ValidationMessageFor(model => model.Notebook.Model)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notebook.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Notebook.Price)
            @Html.ValidationMessageFor(model => model.Notebook.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notebook.RAM)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Notebook.RAM)
            @Html.ValidationMessageFor(model => model.Notebook.RAM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notebook.HDD)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Notebook.HDD)
            @Html.ValidationMessageFor(model => model.Notebook.HDD)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notebook.Monitor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Notebook.Monitor)
            @Html.ValidationMessageFor(model => model.Notebook.Monitor)
        </div>

        <div class="editor-label">
            Производитель
        </div>

        <div class="editor-field">
            <select name="Notebook.Manufacturer.ManufacturerID" style="font-size:12pt; width: 310px;">
                @foreach (var a in Model.Manufacturers)
                {
                    <option value="@a.Value"> @a.Text</option>
                }
            </select>
        </div>

        <div class="editor-label">
            Процессор
        </div>

        <div class="editor-field">
            <select name="Notebook.Processor.ProcessorID" style="font-size:12pt; width: 310px;">
                @foreach (var a in Model.Processors)
                {
                    <option value="@a.Value"> @a.Text</option>
                }
            </select>
        </div>

        <div class="editor-label">
            Пользователь
        </div>

        <div class="editor-field">
            <select name="Notebook.User.UserID" style="font-size:12pt; width: 310px;">
                @foreach (var a in Model.Users)
                {
                    <option value="@a.Value"> @a.Text</option>
                }
            </select>
        </div>

        <p>
            <button type="button" onclick="location.href='@Url.Action("Index", "Notebook")'">Отменить</button>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotebookWebApp/Views/Content/Delete.cshtml
@model NotebookWebApp.Models.Notebook

@{
    ViewBag.Title = "Ноутбук";
}

<h2>Удаление</h2>
<hr />
<h3>Вы действительно хотите удалить этот ноутбук?</h3>
<fieldset>
    <legend>Notebook</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Model): @Html.DisplayFor(model => model.Model)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price): @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RAM): @Html.DisplayFor(model => model.RAM)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HDD): @Html.DisplayFor(model => model.HDD)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Monitor): @Html.DisplayFor(model => model.Monitor)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <button type="button" onclick="location.href='@Url.Action("Index", "Notebook")'">Отменить</button>
        <input type="submit" value="Удалить" />
    </p>
}

NotebookWebApp/Views/Content/Edit.cshtml
@model NotebookWebApp.Models.Notebook

@{
    ViewBag.Title = "Ноутбук";
}

<h2>Редактировать</h2>
<hr />
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Notebook</legend>

        @Html.HiddenFor(model => model.NotebookID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Model)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Model)
            @Html.ValidationMessageFor(model => model.Model)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RAM)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RAM)
            @Html.ValidationMessageFor(model => model.RAM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HDD)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HDD)
            @Html.ValidationMessageFor(model => model.HDD)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Monitor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Monitor)
            @Html.ValidationMessageFor(model => model.Monitor)
        </div>

        <p>
            <button type="button" onclick="location.href='@Url.Action("Index", "Notebook")'">Отменить</button>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotebookWebApp/Views/Content/Index.cshtml
@model IEnumerable<NotebookWebApp.Models.Notebook>

@{
    ViewBag.Title = "Ноутбуки";
}

<h2>Список ноутбуков</h2>
<hr />
<table style="border-spacing: 7px; border-collapse: separate; width: 100%;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RAM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HDD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monitor)
        </th>
        <th>
            Пользователь
        </th>
        <th>
            Процессор
        </th>
         <th>
            Производитель
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RAM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HDD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Monitor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Processor.Model)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.Manufacturer.Name)
        </td>
        <td>
            <button type="button"onclick="location.href='@Url.Action("Edit", "Notebook", new { id=item.NotebookID })'">Редактировать</button>
            <button type="button"onclick="location.href='@Url.Action("Delete", "Notebook", new { id=item.NotebookID })'">Удалить</button>
        </td>
    </tr>
}

</table>
<hr />
<p>
    <button type="button" onclick="location.href='@Url.Action("Create", "Notebook")'">Добавить</button>
</p>